language: java
jdk:
  - openjdk11

env:
  global:
    - PACKAGE_VERSION=1.1-SNAPSHOT
    - PROJECT_NAME=deliSHAs_crawler
    - HANDLER_NAME=Crawler::handleRequest
    - BUCKET_NAME=snupa
    - WAS_URL=http://934d2e64.ngrok.io

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.gradle'

jobs:
  include:
    - stage: build
      before_install:
        - pip install -U pip
        - pip install --user awscli
        - mkdir -p ~/.aws
        - echo -e "[default]\naws_access_key_id = $AWS_ACCESS_KEY\naws_secret_access_key = $AWS_SECRET_KEY" > ~/.aws/credentials
        - cat ~/.aws/credentials
      script: "./gradlew shadowJar"
      deploy:
        - provider: s3
          access_key_id: $AWS_ACCESS_KEY
          secret_access_key: $AWS_SECRET_KEY
          bucket: bapmuksha
          region: ap-northeast-2
          skip_cleanup: true
          acl: public_read
          local_dir: build/libs
          wait-until-deployed: true
          on:
            repo: BaekGeunYoung/deliSHAs_crawler
            branch: master

        - provider: cloudformation
          access_key_id: $AWS_ACCESS_KEY
          secret_access_key: $AWS_SECRET_KEY
          template: cloudformation.yml
          stack_name: DeployCrawler
          edge: true
          wait: true
          parameters:
            - LambdaCodeBucket=$BUCKET_NAME
            - LambdaCodeKey=${PROJECT_NAME}-${PACKAGE_VERSION}-all.jar
            - Lambdahandler=$HANDLER_NAME
            - JdbcUrl=$JDBC_URL
            - JdbcPassword=$JDBC_PASSWORD
            - WasUrl=$WAS_URL
          capabilities: CAPABILITY_IAM
          region: ap-northeast-2
      after_deploy:
        - aws lambda update-function-code --s3-bucket=bapmuksha --s3-key=${PROJECT_NAME}-${PACKAGE_VERSION}-all.jar --region=ap-northeast-2 --function-name=bapmuksha_crawler
