language: java
jdk:
  - openjdk11

env:
  global:
    - PACKAGE_VERSION="1.1-SNAPSHOT"
    - PROJECT_NAME="deliSHAs_crawler"
    - HANDLER_NAME="Crawler::handleRequest"
    - BUCKET_NAME="snupa"

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.gradle'

script: "./gradlew shadowJar"

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: snupa
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: build/libs
    wait-until-deployed: true
    on:
      repo: BaekGeunYoung/deliSHAs_crawler
      branch: master

  - provider: cloudformation
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    template: cloudformation.yml
    stack_name: DeployCrawler
    edge: true
    wait: true
    parameters:
      - LambdaCodeBucket=$BUCKET_NAME
      - LambdaCodeKey="${PROJECT_NAME}-${PACKAGE_VERSION}-all.jar"
      - Lambdahandler=$HANDLER_NAME
    capabilities: CAPABILITY_IAM
    region: ap-northeast-2